### ISSUE TITLE
[BUG] pip install fails for version 0.0.4

### ISSUE THREAD

**Issue by francois-rozet** [JoeriHermans/awflow#2]
```
$ pip install awflow==0.0.4
Collecting awflow==0.0.4
  Using cached awflow-0.0.4.tar.gz (19 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/francois/awf/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ou4rxs3q/awflow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ou4rxs3q/awflow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-ou4rxs3q/awflow/pip-egg-info
         cwd: /tmp/pip-install-ou4rxs3q/awflow/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ou4rxs3q/awflow/setup.py", line 54, in <module>
        'examples': _load_requirements('requirements_examples.txt')
      File "/tmp/pip-install-ou4rxs3q/awflow/setup.py", line 17, in _load_requirements
        with open(file_name, 'r') as file:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements_examples.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by JoeriHermans** [comment]
Fixed in PR #4 and release 0.1.0.
